if (sessionStorage.getItem("school-admin-auth") !== "true") {
  window.location.href = "./login.html";
}

const pageMeta = {
  enrollment: { tag: "\u524D\u53F0\u4E1A\u52A1", title: "\u65B0\u751F\u62A5\u540D\u7BA1\u7406" },
  teacher: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u6559\u5E08\u7BA1\u7406" },
  course: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u5B66\u79D1\u7BA1\u7406" },
  class: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u73ED\u7EA7\u7BA1\u7406" },
  student: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u5B66\u5458\u7BA1\u7406" },
  session: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u4E0A\u8BFE\u7BA1\u7406" },
  charge: { tag: "\u6559\u5B66\u7BA1\u7406", title: "\u6536\u8D39\u6A21\u5F0F" },
  transaction: { tag: "\u8D22\u52A1\u7BA1\u7406", title: "\u6D41\u6C34\u7BA1\u7406" }
};

const campusOptions = ["\u5168\u90E8\u6821\u533A", "\u603B\u90E8\u6821\u533A"];
const retailCategoryOptions = ["\u6559\u6750", "\u914D\u4EF6", "\u4E50\u5668", "\u5B66\u4E60\u7528\u54C1"];

let chargePackages = [];
let courses = [];
let classTypeOptions = ["1\u5BF91", "1\u5BF92", "\u5C0F\u7EC4\u8BFE", "\u73ED\u5236\u8BFE"];
let teachers = [];
let classes = [];
let enrollmentRecords = [];
let retailRecords = [];
let birthdayNotes = {};
let todayRecords = [];
let sessionRecords = [];
let transactions = [];

let currentPage = "student";
let currentBusinessTab = "registration";
let studentStatusFilter = "all";
let editingEnrollmentId = null;
let editingTeacherId = null;
let editingRetailId = null;
let editingCourseId = null;
let editingChargePackageId = null;
let managementEditorMode = "";
let adjustingStudentId = null;
let studentAdjustMode = "class";
let renewingStudentId = null;
let selectedSessionTeacherName = "";
let selectedSessionClassName = "";
let selectedSessionStudentIds = [];

const refs = {
  pageTag: document.getElementById("pageTag"),
  pageTitle: document.getElementById("pageTitle"),
  topSearchBox: document.getElementById("topSearchBox"),
  studentSearch: document.getElementById("studentSearch"),
  exportDataBtn: document.getElementById("exportDataBtn"),
  importDataBtn: document.getElementById("importDataBtn"),
  importDataInput: document.getElementById("importDataInput"),
  logoutBtn: document.getElementById("logoutBtn"),
  toast: document.getElementById("toast"),
  menuParents: Array.from(document.querySelectorAll(".menu-parent")),
  menuItems: Array.from(document.querySelectorAll(".menu-item")),
  businessTabs: Array.from(document.querySelectorAll("[data-business-tab]")),
  businessPanels: Array.from(document.querySelectorAll(".business-panel")),
  contentPanels: Array.from(document.querySelectorAll(".content-panel")),
  studentTableBody: document.getElementById("studentTableBody"),
  resultCount: document.getElementById("resultCount"),
  studentTotalCount: document.getElementById("studentTotalCount"),
  studentClassCount: document.getElementById("studentClassCount"),
  studentBirthdayCount: document.getElementById("studentBirthdayCount"),
  studentStatusFilters: document.getElementById("studentStatusFilters"),
  viewRenewalBtn: document.getElementById("viewRenewalBtn"),
  openSessionManageBtn: document.getElementById("openSessionManageBtn"),
  renewalModal: document.getElementById("renewalModal"),
  renewalList: document.getElementById("renewalList"),
  closeModalBtn: document.getElementById("closeModalBtn"),
  modalMask: document.getElementById("modalMask"),
  renewalFormModal: document.getElementById("renewalFormModal"),
  renewalFormModalMask: document.getElementById("renewalFormModalMask"),
  closeRenewalFormBtn: document.getElementById("closeRenewalFormBtn"),
  renewalFormTitle: document.getElementById("renewalFormTitle"),
  renewalStudentName: document.getElementById("renewalStudentName"),
  renewalCourseName: document.getElementById("renewalCourseName"),
  renewalPackageSelect: document.getElementById("renewalPackageSelect"),
  renewalGiftHoursInput: document.getElementById("renewalGiftHoursInput"),
  renewalReceivableInput: document.getElementById("renewalReceivableInput"),
  renewalDiscountMode: document.getElementById("renewalDiscountMode"),
  renewalDiscountRate: document.getElementById("renewalDiscountRate"),
  renewalDiscountAmount: document.getElementById("renewalDiscountAmount"),
  renewalDiscountRateField: document.getElementById("renewalDiscountRateField"),
  renewalDiscountAmountField: document.getElementById("renewalDiscountAmountField"),
  renewalReceivedInput: document.getElementById("renewalReceivedInput"),
  renewalNoteInput: document.getElementById("renewalNoteInput"),
  saveRenewalBtn: document.getElementById("saveRenewalBtn"),
  cancelRenewalBtn: document.getElementById("cancelRenewalBtn"),
  enrollmentSectionTitle: document.getElementById("enrollmentSectionTitle"),
  enrollDateInput: document.getElementById("enrollDateInput"),
  studentNameInput: document.getElementById("studentNameInput"),
  parentNameInput: document.getElementById("parentNameInput"),
  parentPhoneInput: document.getElementById("parentPhoneInput"),
  studentAgeInput: document.getElementById("studentAgeInput"),
  birthMonthInput: document.getElementById("birthMonthInput"),
  campusSelect: document.getElementById("campusSelect"),
  courseSelect: document.getElementById("courseSelect"),
  classSelect: document.getElementById("classSelect"),
  teacherSelect: document.getElementById("teacherSelect"),
  packageSelect: document.getElementById("packageSelect"),
  giftHoursInput: document.getElementById("giftHoursInput"),
  packageNoteInput: document.getElementById("packageNoteInput"),
  remarkInput: document.getElementById("remarkInput"),
  enrollmentEditHint: document.getElementById("enrollmentEditHint"),
  saveEnrollmentBtn: document.getElementById("saveEnrollmentBtn"),
  resetEnrollmentBtn: document.getElementById("resetEnrollmentBtn"),
  enrollmentCount: document.getElementById("enrollmentCount"),
  enrollmentTableBody: document.getElementById("enrollmentTableBody"),
  birthdayTableBody: document.getElementById("birthdayTableBody"),
  todayDateFilter: document.getElementById("todayDateFilter"),
  todayCourseFilter: document.getElementById("todayCourseFilter"),
  filterTodayBtn: document.getElementById("filterTodayBtn"),
  resetTodayBtn: document.getElementById("resetTodayBtn"),
  todayTableBody: document.getElementById("todayTableBody"),
  addRetailBtn: document.getElementById("addRetailBtn"),
  retailTableBody: document.getElementById("retailTableBody"),
  teacherSearch: document.getElementById("teacherSearch"),
  addTeacherBtn: document.getElementById("addTeacherBtn"),
  teacherListHead: document.getElementById("teacherListHead"),
  teacherCount: document.getElementById("teacherCount"),
  teacherEmptyState: document.getElementById("teacherEmptyState"),
  teacherCardList: document.getElementById("teacherCardList"),
  teacherModal: document.getElementById("teacherModal"),
  teacherModalMask: document.getElementById("teacherModalMask"),
  teacherFormTitle: document.getElementById("teacherFormTitle"),
  closeTeacherModalBtn: document.getElementById("closeTeacherModalBtn"),
  cancelTeacherBtn: document.getElementById("cancelTeacherBtn"),
  saveTeacherBtn: document.getElementById("saveTeacherBtn"),
  teacherName: document.getElementById("teacherName"),
  teacherNickname: document.getElementById("teacherNickname"),
  teacherSubject: document.getElementById("teacherSubject"),
  teacherPhone: document.getElementById("teacherPhone"),
  courseQuickAddBtn: document.getElementById("courseQuickAddBtn"),
  courseTableBody: document.getElementById("courseTableBody"),
  classSearch: document.getElementById("classSearch"),
  addClassTypeBtn: document.getElementById("addClassTypeBtn"),
  addClassBtn: document.getElementById("addClassBtn"),
  newClassInput: document.getElementById("newClassInput"),
  classTypeSelect: document.getElementById("classTypeSelect"),
  classTableBody: document.getElementById("classTableBody"),
  chooseTeacherBtn: document.getElementById("chooseTeacherBtn"),
  sessionTeacherDisplay: document.getElementById("sessionTeacherDisplay"),
  sessionAvailableClassCount: document.getElementById("sessionAvailableClassCount"),
  sessionPendingStudentCount: document.getElementById("sessionPendingStudentCount"),
  sessionViewTabs: document.getElementById("sessionViewTabs"),
  sessionEditorPanel: document.getElementById("sessionEditorPanel"),
  sessionHistoryPanel: document.getElementById("sessionHistoryPanel"),
  sessionLessonDateInput: document.getElementById("sessionLessonDateInput"),
  sessionClassTabs: document.getElementById("sessionClassTabs"),
  sessionStudentList: document.getElementById("sessionStudentList"),
  sessionSelectAllBtn: document.getElementById("sessionSelectAllBtn"),
  sessionResetBtn: document.getElementById("sessionResetBtn"),
  saveSessionBtn: document.getElementById("saveSessionBtn"),
  sessionDateFilter: document.getElementById("sessionDateFilter"),
  sessionTeacherFilter: document.getElementById("sessionTeacherFilter"),
  sessionClassFilter: document.getElementById("sessionClassFilter"),
  filterSessionBtn: document.getElementById("filterSessionBtn"),
  resetSessionFilterBtn: document.getElementById("resetSessionFilterBtn"),
  sessionRecordCount: document.getElementById("sessionRecordCount"),
  sessionPrevPageBtn: document.getElementById("sessionPrevPageBtn"),
  sessionNextPageBtn: document.getElementById("sessionNextPageBtn"),
  sessionPageInfo: document.getElementById("sessionPageInfo"),
  sessionTableBody: document.getElementById("sessionTableBody"),
  sessionTeacherModal: document.getElementById("sessionTeacherModal"),
  sessionTeacherMask: document.getElementById("sessionTeacherMask"),
  closeSessionTeacherModalBtn: document.getElementById("closeSessionTeacherModalBtn"),
  sessionTeacherList: document.getElementById("sessionTeacherList"),
  addChargePackageBtn: document.getElementById("addChargePackageBtn"),
  chargePackageList: document.getElementById("chargePackageList"),
  chargePackageModal: document.getElementById("chargePackageModal"),
  chargePackageModalMask: document.getElementById("chargePackageModalMask"),
  closeChargePackageModalBtn: document.getElementById("closeChargePackageModalBtn"),
  chargePackageFormTitle: document.getElementById("chargePackageFormTitle"),
  chargePackageNameInput: document.getElementById("chargePackageNameInput"),
  chargePackageHoursInput: document.getElementById("chargePackageHoursInput"),
  chargePackagePriceInput: document.getElementById("chargePackagePriceInput"),
  saveChargePackageBtn: document.getElementById("saveChargePackageBtn"),
  cancelChargePackageBtn: document.getElementById("cancelChargePackageBtn"),
  transactionDateFrom: document.getElementById("transactionDateFrom"),
  transactionDateTo: document.getElementById("transactionDateTo"),
  transactionCampusFilter: document.getElementById("transactionCampusFilter"),
  transactionCourseFilter: document.getElementById("transactionCourseFilter"),
  transactionCategoryFilter: document.getElementById("transactionCategoryFilter"),
  transactionTypeFilter: document.getElementById("transactionTypeFilter"),
  transactionStudentKeyword: document.getElementById("transactionStudentKeyword"),
  transactionItemKeyword: document.getElementById("transactionItemKeyword"),
  filterTransactionBtn: document.getElementById("filterTransactionBtn"),
  resetTransactionBtn: document.getElementById("resetTransactionBtn"),
  transactionTotalAmount: document.getElementById("transactionTotalAmount"),
  transactionTuitionAmount: document.getElementById("transactionTuitionAmount"),
  transactionRetailAmount: document.getElementById("transactionRetailAmount"),
  transactionOtherAmount: document.getElementById("transactionOtherAmount"),
  transactionTableBody: document.getElementById("transactionTableBody"),
  transactionPrevPageBtn: document.getElementById("transactionPrevPageBtn"),
  transactionPageInfo: document.getElementById("transactionPageInfo"),
  transactionNextPageBtn: document.getElementById("transactionNextPageBtn"),
  retailModal: document.getElementById("retailModal"),
  retailModalMask: document.getElementById("retailModalMask"),
  retailFormTitle: document.getElementById("retailFormTitle"),
  closeRetailModalBtn: document.getElementById("closeRetailModalBtn"),
  cancelRetailBtn: document.getElementById("cancelRetailBtn"),
  saveRetailBtn: document.getElementById("saveRetailBtn"),
  retailDateInput: document.getElementById("retailDateInput"),
  retailItemInput: document.getElementById("retailItemInput"),
  retailCategoryInput: document.getElementById("retailCategoryInput"),
  retailCampusInput: document.getElementById("retailCampusInput"),
  retailCourseInput: document.getElementById("retailCourseInput"),
  retailQuantityInput: document.getElementById("retailQuantityInput"),
  retailUnitPriceInput: document.getElementById("retailUnitPriceInput"),
  retailAmountInput: document.getElementById("retailAmountInput"),
  retailBuyerInput: document.getElementById("retailBuyerInput"),
  retailPaymentInput: document.getElementById("retailPaymentInput"),
  retailOperatorInput: document.getElementById("retailOperatorInput"),
  retailRemarkInput: document.getElementById("retailRemarkInput"),
  managementEditorModal: document.getElementById("managementEditorModal"),
  managementEditorMask: document.getElementById("managementEditorMask"),
  closeManagementEditorBtn: document.getElementById("closeManagementEditorBtn"),
  cancelManagementEditorBtn: document.getElementById("cancelManagementEditorBtn"),
  managementEditorTitle: document.getElementById("managementEditorTitle"),
  managementEditorHint: document.getElementById("managementEditorHint"),
  managementEditorLabel: document.getElementById("managementEditorLabel"),
  managementEditorInput: document.getElementById("managementEditorInput"),
  saveManagementEditorBtn: document.getElementById("saveManagementEditorBtn"),
  studentAdjustModal: document.getElementById("studentAdjustModal"),
  studentAdjustMask: document.getElementById("studentAdjustMask"),
  closeStudentAdjustBtn: document.getElementById("closeStudentAdjustBtn"),
  cancelStudentAdjustBtn: document.getElementById("cancelStudentAdjustBtn"),
  saveStudentAdjustBtn: document.getElementById("saveStudentAdjustBtn"),
  studentAdjustTitle: document.getElementById("studentAdjustTitle"),
  adjustStudentName: document.getElementById("adjustStudentName"),
  adjustCourseField: document.getElementById("adjustCourseField"),
  adjustClassField: document.getElementById("adjustClassField"),
  adjustTeacherField: document.getElementById("adjustTeacherField"),
  adjustCourseSelect: document.getElementById("adjustCourseSelect"),
  adjustClassSelect: document.getElementById("adjustClassSelect"),
  adjustTeacherSelect: document.getElementById("adjustTeacherSelect"),
  adjustEffectiveDate: document.getElementById("adjustEffectiveDate"),
  adjustNoteInput: document.getElementById("adjustNoteInput")
};
